services:
  front-end:
    build:
      context: front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end/src:/app/src
      - /app/node_modules
    networks:
      - news-article
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    image: back-end
    container_name: back-end
    restart: unless-stopped
    working_dir: /var/www/back-end
    volumes:
      - ./back-end:/var/www/back-end
    networks:
      - news-article
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./back-end:/var/www/back-end
      - ./nginx:/etc/nginx/conf.d
    networks:
      - news-article
  mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_PASSWORD: db_password
      MYSQL_USER: db_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - news-article

networks:
  news-article:
    driver: bridge